---
elastic:
  proto: https
  host: host
  port: 9200
  username: user
  password: pass
  indexes:
          ip_address: vt-comments-ip_address
          graph: vt-comments-graph
          file: vt-comments-file
          domain: vt-comments-domain
          url: vt-comments-url
vt:
  key: XXXXX
  comment_authors:
          - author1
          - author2
          - ...
